version: "3.9"  # optional since v1.27.0
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: db
    hostname: db
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=P@ssw0rd"
    ports:
      - "1433:1433"
    volumes:
      - "mssql-azuresql-edge-data:/var/opt/mssql"
  web_api:
    image: aviato
    container_name: aviato
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      - "ASPNETCORE_HTTP_PORT=https://+:5001"
      - "ASPNETCORE_URLS=http://+:5002"
      - "ASPNETCORE_ENVIRONMENT=Development"
volumes:
  mssql-azuresql-edge-data:
  sqlpad-volume: